name: deployment_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6
- nb_conda
- tornado
- urllib3
- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - papermill==1.0.1
  - python-dotenv==0.10.3
  - Pillow==6.1.0
  - torch==1.1.0
  - torchvision==0.3
  - matplotlib==3.1.1
  - toolz==0.9.0
  - tqdm==4.32.2
  - azure-cli==2.0.63
  - azureml-sdk[notebooks, contrib]==1.0.45
  - prompt-toolkit==2.0.9

